apiVersion: apps/v1 
kind: Deployment
metadata:
  name: model-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-server
  template:
    metadata:
      labels:
        app: model-server
    spec:
      containers:
      - name: model-server
        image: model-server:latest
        imagePullPolicy: Never
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"

        ports:
        - containerPort: 8000
        env:
          - name: REDIS_HOST
            valueFrom:
              configMapKeyRef:
                name: redis-config
                key: hostname
          - name: REDIS_PORT
            valueFrom:
              configMapKeyRef:
                name: redis-config
                key: port
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-secret
                key: db_password
          - name: PROJECT_ROOT
            valueFrom:
              configMapKeyRef:
                name: model-server-config
                key: project_root