apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: default
  labels:
    app: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: web-server
        image: web-server:latest
        imagePullPolicy: Never
        resources:
          requests:
            memory: "100Mi"
            cpu: "250m"
          limits:
            memory: "200Mi"
            cpu: "500m"
        ports:
          - containerPort: 9000
        env:
          - name: REDIS_HOST
            valueFrom:
              configMapKeyRef:
                name: redis-config
                key: hostname
          - name: REDIS_PORT
            valueFrom:
              configMapKeyRef:
                name: redis-config
                key: port
          - name: MODEL_SERVER_URL
            valueFrom:
              configMapKeyRef:
                name: model-server-config
                key: model_server_url
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-secret
                key: db_password
          - name: PROJECT_ROOT
            valueFrom:
              configMapKeyRef:
                name: model-server-config
                key: project_root
