apiVersion: v1
kind: ConfigMap
metadata:
    name: model-server-config-{{ .Values.configVersions.modelServer }}
    namespace: {{ .Values.namespace }}
    labels:
        app.kubernetes.io/name: model-server
        app.kubernetes.io/part-of: mnist-app
        app.kubernetes.io/version: {{ .Values.configVersions.modelServer }}
data:
    model_server_url: {{ .Values.modelServerUrl }}
    project_root: {{ .Values.projectRoot }}