apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config-{{ .Values.configVersions.redis }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/version: {{ .Values.configVersions.redis }}
    app.kubernetes.io/part-of: mnist-app
data:
  hostname: redis-service
  port: "6379"