
_target_: src.models.catdog_classifier_convnext.ConvNextClassifier

# model params
base_model: convnext_tiny.in12k_ft_in1k
pretrained: True
num_classes: 2
kernel_sizes: 7
# optimizer params
lr: 1e-3
weight_decay: 1e-5

# scheduler params
factor: 0.1
patience: 10
min_lr: 1e-6