_target_: src.models.catdog_model_resnet.ResnetClassifier

# model params
base_model: efficientnet_b0
pretrained: True
num_classes: 2
# optimizer params
lr: 1e-3
weight_decay: 1e-5
# scheduler params
factor: 0.1
patience: 10
min_lr: 1e-6
