
# model class
_target_: src.models.catdog_model.ViTTinyClassifier

# model params
img_size: ${data.image_size}
patch_size: 16
num_classes: 2
embed_dim: 128
depth: 6
num_heads: 4
mlp_ratio: 4
pre_norm: False

# optimizer params
lr: 1e-3
weight_decay: 1e-5

# scheduler params
factor: 0.1
patience: 10
min_lr: 1e-6