defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.ckpt_dir}
  monitor: "val_loss"
  mode: "min"
  save_last: False
  auto_insert_metric_name: False

early_stopping:
  monitor: "val_loss"
  patience: 3
  mode: "min"

model_summary:
  max_depth: -1