# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: catdog
  - model: catdog_model
  - callbacks: default
  - logger: null # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
  - trainer: default
  - paths: dogbreed
  - hydra: default
  # experiment configs allow for version control of specific hyperparameters
  # e.g. best hyperparameters for given model and datamodule
  - experiment: catdog_experiment
  # debugging config (enable through command line, e.g. `python train.py debug=default)
  - debug: null

# task name, determines output directory path
task_name: "infer"

# tags to help you identify your experiments
# you can overwrite this in experiment configs
# overwrite from command line with `python train.py tags="[first_tag, second_tag]"`
tags: ["dev"]

# set False to skip model training
train: False

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: False

# simply provide checkpoint path to resume training
ckpt_path: ${paths.ckpt_dir}/best-checkpoint.ckpt

# seed for random number generators in pytorch, numpy and python.random
seed: 42

# name of the experiment
name: "catdog_experiment"

server:
  port: 8080
  max_batch_size: 8
  batch_timeout: 0.01
  accelerator: "auto"
  devices: "auto"
  workers_per_device: 2

labels: ["cat", "dog"]