defaults:
  - _self_
  - data: dogbreed
  - model: dogbreed_classifier
  - callbacks: default
  - logger: null
  - trainer: default
  - paths: default  # This should map to another config file if using hydra to merge

task_name: train
tags:
  - dev
train: true
test: true
ckpt_path: null
seed: 42

# Ensure paths section is present
paths:
  root_dir: ./  # Project root directory
  data_dir: ./data  # Path to your dataset
  log_dir: ./logs  # Path to logs directory
  ckpt_dir: ./checkpoints  # Path to checkpoints
  artifact_dir: ./artifacts  # Path to save artifacts
  kaggle_dir: khushikhushikhushi/dog-breed-image-dataset  # Path for Kaggle dataset

# Ensure data section is present
data:
  num_workers: 4
  batch_size: 32
  image_size: 224
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
