# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: catdog
  - model: catdog_classifier
  - callbacks: default
  - logger: default # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
  - trainer: default
  - paths: catdog
  - hydra: default

  - experiment: catdog_experiment
  # debugging config (enable through command line, e.g. `python train.py debug=default)
  - debug: null

# task name, determines output directory path
task_name: "train"

# tags to help you identify your experiments
# you can overwrite this in experiment configs
# overwrite from command line with `python train.py tags="[first_tag, second_tag]"`
tags: ["dev"]

# set False to skip model training
train: True

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: False

# simply provide checkpoint path to resume training
ckpt_path: ${paths.ckpt_dir}/best-checkpoint.ckpt

# seed for random number generators in pytorch, numpy and python.random
seed: 42

# name of the experiment
name: "catdog_experiment"

# optimization metric
optimization_metric: "val_acc"

# optuna hyperparameter optimization
n_trials: 2

labels: ["cat", "dog"]