name: Deploy PyTorch Training to ECR with Docker Compose

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    if: github.ref_name == 'main' || github.ref_name == 'feat/pytorch-catdog-setup'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create .env file
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env

      - name: Build Docker image with .env
        env:
          REGISTRY: ${{ secrets.AWS_REGISTRY }}
          REPOSITORY: soutrik71/pytorch_catdog
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .

      - name: Run Docker Compose for train service
        run: |
          docker-compose up -d --build train  # Start only the `train` service

      - name: Tag Docker image
        env:
          REGISTRY: ${{ secrets.AWS_REGISTRY }}
          REPOSITORY: soutrik71/pytorch_catdog
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker tag $REGISTRY/$REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:latest

      - name: Push Docker image to ECR
        env:
          REGISTRY: ${{ secrets.AWS_REGISTRY }}
          REPOSITORY: soutrik71/pytorch_catdog
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:latest

      - name: Pull Docker image from ECR and verify
        env:
          REGISTRY: ${{ secrets.AWS_REGISTRY }}
          REPOSITORY: soutrik71/pytorch_catdog
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker pull $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker images | grep "$REGISTRY/$REPOSITORY"
